### ISSUE TITLE
how to train our own dataset?

### ISSUE THREAD

**Issue by mer93** [praeclarumjj3/VQ-VAE-on-MNIST#1]
If the dataset is in the form of images?

**Comment by praeclarumjj3** [comment]
You can write your own [custom data loader](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html#dataset-class). @mer93

**Comment by mer93** [comment]
resolved

**Comment by praeclarumjj3** [comment]
> I have used my own data loader , still the model is not training. Could you please guide me more how I can start training on my dataset?
> 
> Thanks

Could you share the exact issue that you are facing? Is the training not started, the performance is not good, or some other error?

**Comment by praeclarumjj3** [comment]
> > I have used my own data loader , still the model is not training. Could you please guide me more how I can start training on my dataset?
> > Thanks
> 
> Could you share the exact issue that you are facing? Is the training not started, the performance is not good, or some other error?
